### ISSUE TITLE
PyPi package is not available for python 3.10

### ISSUE THREAD

**Issue by marshall7m** [Scalr/pygohcl#12]
pip version: `22.2.2`
I'm trying to install the package from PyPi. When I run `pip install pygohcl`, I get the following error:
```
ERROR: Could not find a version that satisfies the requirement pygohcl (from versions: none)
ERROR: No matching distribution found for pygohcl
```

Also tried pinning the version via the command ` pip install pygohcl==1.0.4` but get a similar error:
```
ERROR: Could not find a version that satisfies the requirement pygohcl==1.0.4 (from versions: none)
ERROR: No matching distribution found for pygohcl==1.0.4
```

**Comment by recipe** [comment]
@marshall7m Please check you `python --version` and `arch`. The list of available python packages are here https://pypi.org/project/pygohcl/#files

**Comment by marshall7m** [comment]
Oops silly me was using python 3.10. Thanks for the quick response @recipe

**Comment by recipe** [comment]
Added in `pygohcl==1.0.6`.
